### ISSUE TITLE
Check if PHP version is installed

### ISSUE THREAD

**Issue by djbe** [appwise-labs/sysops-phpenv#1]
Someone tried switching from 7.3 to 7.1, the latter not installed on the system.
Got stuck with a partially working setup, that he couldn't get out of.

We should add checks for:
- phpenv -> see if version is installed
- reload -> see if target version is installed
If a version is not found, give a nice error message and list available versions.

**Comment by wassup-** [comment]
Great idea! I have committed the necessary changes for this.
